name: 99-Destroy Resources

on:
  workflow_dispatch:

permissions:
  contents: read
  issues: write
  pull-requests: write
  id-token: write

jobs:
  plan:
    name: Terraform Plan
    runs-on: ubuntu-latest

    steps:
      # Use a role for OIDC authentication
      - name: Configure AWS Credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.AWS_ROLE_ARN }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.14.3

      - name: Terraform Init
        id: init
        run: |
          terraform init \
            -backend-config="bucket=${{ vars.TERRAFORM_STATE_BUCKET }}" \
            -backend-config="key=${{ github.repository }}" \
            -backend-config="region=${{ vars.AWS_REGION }}"

      - name: Terraform Plan
        continue-on-error: true
        id: plan
        run: |
          terraform plan -destroy -input=false -no-color -out=tfplan
          terraform show -no-color tfplan > plan.txt
      - name: Display the plan summary
        id: display
        run: |
          {
            awk '/No changes. No objects need to be destroyed./ {
              print "## " $0
              print "Either you have not created any objects yet or the existing objects were already deleted outside of Terraform."
              exit
            }' plan.txt

            awk '/Terraform will perform the following actions:/ {
              print "## Terraform will perform the following actions:"
              print "|Action|Resource|"
              print "|------|--------|"
              exit
            }' plan.txt

            awk '/Terraform used the selected/{ next } /will be/ || /must be/ {print "|" $5 "|" $2 "|"; next} /Plan:/{ print "## " $0; next }' plan.txt \
              | sed -e 's/created/:white_check_mark: create/' -e 's/destroyed/:bangbang: destroy/' -e 's/replaced/:recycle: replace/'
          } > plan.md
          cat plan.md >> $GITHUB_STEP_SUMMARY

      - name: Update PR comments
        if: github.event_name == 'pull_request'
        id: comment
        uses: peter-evans/create-or-update-comment@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.number }}
          body-path: plan.md
  apply:
    needs: [plan]
    if: github.ref == 'refs/heads/main'
    name: Terraform Apply
    runs-on: ubuntu-latest
    environment: Production
    concurrency: Production

    steps:
      # Use a role for OIDC authentication
      - name: Configure AWS Credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.AWS_ROLE_ARN }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.14.3

      - name: Terraform Init
        id: init
        run: |
          terraform init \
            -backend-config="bucket=${{ vars.TERRAFORM_STATE_BUCKET }}" \
            -backend-config="key=${{ github.repository }}" \
            -backend-config="region=${{ vars.AWS_REGION }}"

      - name: Terraform Apply
        id: apply
        run: terraform apply -destroy -no-color -auto-approve -input=false | tee apply.txt

      - name: Display the apply summary
        id: display
        run: |
          {
            awk '/::debug::stdout:/{ next } /Apply complete!/ { print "## " $0; exit }' apply.txt
          } > apply.md

          cat apply.md >> $GITHUB_STEP_SUMMARY
